version: 2
jobs:
  build_windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run: yarn && yarn release --x64 --ia32 --linux --win

  build_macos:
    macos:
      xcode: "14.0.0"
    steps:
      - checkout
      - run: yarn && yarn release

workflows:
  version: 2
  build:
    jobs:
      - build_windows
      - build_macos